# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/digilent-xdc-master/Arty-A7-35-Master.xdc

# IP: ip/Clk_gen_pll/Clk_gen_pll.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Clk_gen_pll || ORIG_REF_NAME==Clk_gen_pll} -quiet] -quiet

# XDC: c:/Users/franc/Documents/GitHub/ELEC-490/BPSK_Modulation/BPSK_Modulation.gen/sources_1/ip/Clk_gen_pll/Clk_gen_pll_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Clk_gen_pll || ORIG_REF_NAME==Clk_gen_pll} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/franc/Documents/GitHub/ELEC-490/BPSK_Modulation/BPSK_Modulation.gen/sources_1/ip/Clk_gen_pll/Clk_gen_pll.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Clk_gen_pll || ORIG_REF_NAME==Clk_gen_pll} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/franc/Documents/GitHub/ELEC-490/BPSK_Modulation/BPSK_Modulation.gen/sources_1/ip/Clk_gen_pll/Clk_gen_pll_ooc.xdc
